config/routes.rb
Rails.application.routes.draw do
  resources :revenues do
    collection do
      get '(/:category(/:timeframe))', :action => :index
    end
  end
  resources :expenses do
    collection do
      get '(/:category(/:timeframe))', :action => :index
    end
  end
  resources :net do
    collection do
    end
  end
  resources :enrollments do
    collection do
      get '(/:category(/:timeframe))', :action => :index
    end
  end
  resources :customers do
    collection do
    end
  end
  resources :churn do
    collection do
    end
  end
  #for testing hireology widget
  resources :test do
    collection do
    end
  end
  root :to => "revenues#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TLGWA Monthly <%= params[:controller].capitalize %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <span class="navbar-brand">TLG West Ashley</span>
      <ul class="nav navbar-nav">
        <li <%= active_page("revenues") %>><%= link_to "Revenue", relative_url + revenues_path %></li>
        <li <%= active_page("expenses") %>><%= link_to "Expenses", relative_url + expenses_path %></li>
        <li <%= active_page("net") %>><%= link_to "Net", relative_url + net_index_path %></li>
        <li <%= active_page("enrollments") %>><%= link_to "Enrollments", relative_url + enrollments_path %></li>
      </ul>
    </div>
  </div>
</nav>
<%= yield %>
</body>
</html>